import React, { useEffect, useState } from 'react';
import { FileCheck, Download, Search } from 'lucide-react';
import { reportsApi } from '../services/api';

export default function ReportsPage() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    reportsApi.list()
      .then(res => setReports(res.data || []))
      .catch(err => console.error(err))
      .finally(() => setLoading(false));
  }, []);

  const filteredReports = reports.filter(r => {
    const q = searchTerm.toLowerCase();
    return !q || (r.filename && r.filename.toLowerCase().includes(q));
  });

  return (
    <div className="space-y-6 max-w-7xl mx-auto">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight flex items-center gap-2 font-sans">
            <FileCheck className="w-6 h-6 text-indigo-600" />
            <span>Generated Regulatory Evaluation Reports</span>
          </h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Formal PDF evaluation reports generated by ReportLab compliance engine.
          </p>
        </div>

        <div className="relative">
          <Search className="w-3.5 h-3.5 text-slate-400 absolute left-3 top-2.5" />
          <input
            type="text"
            placeholder="Search report files..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="bg-white border border-slate-200 rounded-xl pl-8 pr-3 py-1.5 text-xs text-slate-800 focus:outline-none focus:border-indigo-500 w-48 sm:w-64 shadow-2xs"
          />
        </div>
      </div>

      {/* Reports Table */}
      <div className="bg-white border border-slate-200/90 rounded-2xl overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-slate-700">
            <thead className="bg-slate-50 text-slate-500 font-mono uppercase text-[10px] border-b border-slate-200">
              <tr>
                <th className="p-4 font-bold">Report Document Filename</th>
                <th className="p-4 font-bold">File Size</th>
                <th className="p-4 font-bold">Date Generated</th>
                <th className="p-4 text-right font-bold">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 font-sans">
              {loading ? (
                <tr>
                  <td colSpan={4} className="p-8 text-center text-slate-400">Loading reports...</td>
                </tr>
              ) : filteredReports.length > 0 ? (
                filteredReports.map((r, idx) => (
                  <tr key={idx} className="hover:bg-slate-50/80 transition">
                    <td className="p-4 font-mono text-slate-900 font-bold flex items-center gap-2.5">
                      <div className="w-8 h-8 rounded-lg bg-emerald-50 border border-emerald-200 flex items-center justify-center text-emerald-600 shrink-0">
                        <FileCheck className="w-4 h-4" />
                      </div>
                      <span className="text-xs">{r.filename}</span>
                    </td>
                    <td className="p-4 font-mono text-slate-500 font-medium">{(r.size_bytes / 1024).toFixed(1)} KB</td>
                    <td className="p-4 font-mono text-slate-500">{new Date(r.created_at * 1000).toLocaleString()}</td>
                    <td className="p-4 text-right">
                      <a
                        href={r.download_url}
                        download
                        className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white font-bold transition inline-flex items-center gap-1.5 shadow-md shadow-emerald-600/20 text-xs cursor-pointer"
                      >
                        <Download className="w-3.5 h-3.5" />
                        <span>Download PDF</span>
                      </a>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan={4} className="p-8 text-center text-slate-400">
                    No PDF reports generated yet. Click "Generate PDF Report" on any evaluation detail page.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
